### ISSUE TITLE
[java] Incorrect type resolution with classes having the same name

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#913] opened 2018-02-14 18:12 UTC
We have two classes named AttributeAxisIterator, one in package n.s.pmd.lang.ast.xpath and one in n.s.pmd.lang.ast.xpath.saxon. It seems that the second one is resolved to the type of the first one. Try copy pasting the contents of n.s.pmd.lang.ast.xpath.saxon.AttributeAxisIterator in the designer, you'll see that typeof returns the wrong type on the type declaration

**Comment by jsotuyod** [comment] 2024-04-28 05:05
I don't think this is reproducible in PMD 7…

The classes mentioned were only part of PMD 6.x, and given the time of the report (2018), it seems to be a report on PMD 6.x anyway.

I'm closing it as fixed for the time being.

**Closed by jsotuyod** 2024-04-28 05:05 UTC
Labels: in:type-resolution, in:symbol-table
