### ISSUE TITLE
[cpd] CLI should support outputting to a file

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#5119] opened 2024-07-17 14:34 UTC
CPD in CLI should also support `--report-file <path>` / `-r <path>` flags.

When running from Ant, an output file can be passed along, but CLI doesn't support this natively.

Right now, the only way to output to a file is relying on stdout output redirection.

**Comment by adangel** [comment] 2024-07-18 08:34
Duplicate of #4653

**Closed by adangel** 2024-07-18 08:34 UTC
Labels: was:duplicate, an:enhancement, in:cpd, in:cli
