### ISSUE TITLE
[java] NPE when resolving nested class dependency

### ISSUE THREAD

**Issue by dmitrykuzmin** [pmd/pmd#1705] opened 2019-03-01 12:11 UTC
**Affects PMD Version:** 6.11.0

**Rule:** any

**Running PMD through:** *Gradle*

**Code Sample demonstrating the issue:**
Working example [here](https://github.com/dmitrykuzmin/pmd-test) . To reproduce the error run
```
./gradlew build
```

**Description:** 
When there is a class like this
```java
public class Class1 {
    public class InnerClass1 {}
    public class InnerClass2 extends ThirdPartyDependencyClass {}
}
```
in `moduleA` and some other `moduleB` depends on `moduleA` and imports `Class1.InnerClass1`, the PMD check on `moduleB` fails with NPE.

Stacktrace:
```
...
Caused by: java.lang.NullPointerException
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateType(ClassTypeResolver.java:1361)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateType(ClassTypeResolver.java:1293)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:229)
        at net.sourceforge.pmd.lang.java.ast.ASTImportDeclaration.jjtAccept(ASTImportDeclaration.java:135)
        at net.sourceforge.pmd.lang.java.ast.AbstractJavaNode.childrenAccept(AbstractJavaNode.java:60)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:11)
        at net.sourceforge.pmd.lang.java.ast.JavaParserVisitorAdapter.visit(JavaParserVisitorAdapter.java:181)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:213)
        at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:41)
        at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:18)
        at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:121)
        at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:153)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:180)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:96)
        ... 135 more
```
It seems like PMD tries to resolve the `ThirdPartyDependencyClass` which is not available on `moduleB` compile classpath.

Using runtime classpath like this
```gradle
pmdMain.classpath += sourceSets.main.runtimeClasspath
```
in `moduleB` "fixes" the issue, but I'm not sure it's working as intended.

Importing `Class1.InnerClass2` or `Class1` itself for the same code snippet does not lead to an error.

This may be related to #1532.

**Comment by jsotuyod** [comment] 2019-04-01 16:28
Thanks for the report! This is effectively a duplicate of #1532, I'm closing this to track it in the original report.

**Closed by jsotuyod** 2019-04-01 16:28 UTC
