### ISSUE TITLE
[java] controversial.AvoidLiteralsInIfCondition 0.0 false positive 

### ISSUE THREAD

**Issue by Reissner** [pmd/pmd#388] opened 2017-05-08 12:57 UTC
I run pmd 5.6.1. via maven. 

Ruleset is 

~~~
  <rule ref="rulesets/java/controversial.xml/AvoidLiteralsInIfCondition">
    <properties>
      <property name="ignoreMagicNumbers"    value="-1,0,1, 0.0"/>
    </properties>
   </rule>
~~~

Code is (starting with line 1490) 

~~~
	if (num == 0.0) {
	    return MathExtItg.sgn0raw(num) == 1 
		? IEEEclass.PositiveZero      : IEEEclass.NegativeZero;
	}
~~~

Still is reported 

`Avoid using Literals in Conditional Statements 	1490`

Please don't tell me that `num==0.0` is bad coding: this is a very special use case.

**Comment by oowekyala** [comment] 2017-05-10 09:42
I don't think that's a false positive, this seems to be the type of code the rule is made to report. If it's a special use case and you don't want to change it you can suppress the violation with a `//NOPMD` comment on the line of the `if`, or disable the rule for the whole method by annotating the method with `@SuppressWarnings("PMD.AvoidLiteralsInIfCondition")`

**Comment by Reissner** [comment] 2017-05-10 09:49
Sorry, I did not manage to give the ruleset. it is 
  <rule ref="rulesets/java/controversial.xml/AvoidLiteralsInIfCondition">
    <properties>
      <property name="ignoreMagicNumbers"    value="-1,0,1, 0.0"/>
    </properties>
   </rule>

explicitly mentioning 0.0 as to be ignored. 
That is the way I would like to mute the rule here.

**Comment by Reissner** [comment] 2017-05-10 09:50
Sorry, I did not manage to give the ruleset. it is

  &lt;rule ref="rulesets/java/controversial.xml/AvoidLiteralsInIfCondition">
    &lt;properties>
      &lt;property name="ignoreMagicNumbers"    value="-1,0,1, 0.0"/>
    &lt;/properties>
   &lt;/rule>



explicitly mentioning 0.0 as to be ignored.
That is the way I would like to mute the rule here.

**Comment by oowekyala** [comment] 2017-05-10 10:40
Oh my bad, I didn't know that. That would indeed be the preferred way to mute the rule. I can't reproduce your bug however, for me adding 0.0 to the property correctly ignores the sample code :/

**Comment by oowekyala** [comment] 2017-05-10 10:41
Oh no ! I've spotted the bug. Just remove the space that precedes `0.0` in the value of ignoreMagicNumbers

**Comment by jsotuyod** [comment] 2017-05-15 07:25
@Reissner please confirm the suggested fix works for you.

On our end we should make sure this is either producing a proper warning or, ideally, a config error. That way we would completely get over this when fixing #194

**Comment by jsotuyod** [comment] 2017-05-15 13:43
The solution by @oowekyala is confirmed, we should just check the config error is generated before closing this.

**Comment by Reissner** [comment] 2017-05-16 07:36
Well, this is not really a fix, it is a workaround. But anyway, i can live with that. 
At least one should document that blanks are not allowed. (something like separated by , without blanks)
Much better would be to allow blanks still.

**Comment by adangel** [comment] 2017-05-23 18:30
Would be nice, if PMD itself would trim any whitespaces. However, this is a [XPath rule](https://pmd.github.io/pmd-5.7.0/pmd-java/rules/java/controversial.html#AvoidLiteralsInIfCondition), so it's probably a bit more difficult.

Might be simpler though - tokenize uses a regex: Would using `tokenize($ignoreMagicNumbers, '\s*,\s*')` work already?

**Comment by jsotuyod** [comment] 2017-09-09 21:57
@oowekyala was kind enough to submit a PR with the suggested fix and test case. This will be part of PMD 6.0.0

**Closed** 2017-09-09 21:56 UTC
Labels: a:false-positive, has:pr

**Comment by Fernal73** [comment] 2019-06-21 23:48
This rule could be amended to allow for a counter variable to be exceeded before this error is flagged. It's unrealistic to expect developers to use constants for every literal value. Of course, it could be commented out using NO PMD, but I'd like to keep that to a minimum.
