### ISSUE TITLE
[doc] CLI reference for `-norulesetcompatibility` shows a boolean default value

### ISSUE THREAD

**Issue by jsotuyod** [pmd/pmd#2058] opened 2019-10-05 22:09 UTC
I added the option -norulesetcompatibility true to the PMD script right
after the -min 1 and it displays the PMD CLI help.

It's the same with -norulesetcompatibility false. The default as listed in
the CLI options is false.

https://pmd.github.io/latest/pmd_userdocs_cli_reference.html#options

_Originally posted by @Fernal73 in https://github.com/pmd/pmd/issues/1794#issuecomment-538648246_

The doc is misleading, as this is a flag without an actual value. This applies to several other values to such as `-help`, `-verbose`, `-no-cache`, `-stress` and many more.

**Comment by Fernal73** [comment] 2019-10-06 03:35
The option is not available in the ant task.
https://pmd.github.io/latest/pmd_userdocs_tools_ant.html#parameters

It doesn't appear to be available in the Maven plugin either. I see no mention of the parameter .

**Comment by oowekyala** [comment] 2019-10-06 14:28
This was fixed in https://github.com/pmd/pmd/commit/7f936e3c38e0b8da72c5db11d7818f2069f875f7

**Comment by Fernal73** [comment] 2019-10-06 14:55
The issue is in the documentation. I see now that there is no value to be set for this option. It's either used or omitted. The problem is with the Default Value column. That misled me to believe that a value could be set for the switch.

**Comment by oowekyala** [comment] 2019-10-06 15:08
First column:  `-min <num>` obviously expects an argument, `-no-cache` expects none. Now those options will have an empty cell in the default value column. How is this unclear and how would you make it better?

**Comment by Fernal73** [comment] 2019-10-06 15:21
Actually, it seems silly now that I understand the documentation and the proper use of the switch. You'd need a fresh pair of eyes to find fault in the documentation. The switch is self-explanatory. It doesn't need a default value to be displayed. The documentation could omit mentioning the presence of a filter. It confuses the reader. It could simply read "Disables automatic 'fixing' of old ruleset files with old rule names". And then explain what happens without the switch. There is no need to mention a filter; it's an implementation detail and it's internal, as I understand it.

**Closed** 2019-10-09 20:13 UTC
Labels: an:enhancement, good first issue, in:documentation
