### ISSUE TITLE
[java] CPD runs into NPE when analyzing Lucene

### ISSUE THREAD

**Issue by eldereng** [pmd/pmd#185] opened 2017-01-11 12:04 UTC
I use pmd-4.2.6.jar to detect clones with "net.sourceforge.pmd.cpd.GUI" (java -Xmx4g -XX:-UseGCOverheadLimit  -cp pmd-4.2.6.jar net.sourceforge.pmd.cpd.GUI). To this version, I run with parameters -Xmx4g -XX:-UseGCOverheadLimit (I use Linux 64bits with 28GB of RAM). To detect clones I use "Ignore Literals and Identifiers=true" and "Scan subdiretories=true". This version is OK.

Today, I updated to latest version PMD-5.5.2 (5th November 2016). I runned this version with script "run.sh" (./run.sh cpdgui) in folder "bind". However  this version show some erros:

Error 1: When the flag "Ignore identifiers" is true, the tool show the follow message:
java.lang.NullPointerException
	at net.sourceforge.pmd.cpd.JavaTokenizer$ConstructorDetector.processToken(JavaTokenizer.java:235)
	at net.sourceforge.pmd.cpd.JavaTokenizer.processToken(JavaTokenizer.java:76)
	at net.sourceforge.pmd.cpd.JavaTokenizer.tokenize(JavaTokenizer.java:54)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:143)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:138)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:103)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:67)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:77)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:62)
	at net.sourceforge.pmd.cpd.GUI.go(GUI.java:624)
	at net.sourceforge.pmd.cpd.GUI.access$500(GUI.java:70)
	at net.sourceforge.pmd.cpd.GUI$GoListener$1.run(GUI.java:198)
	at java.lang.Thread.run(Unknown Source)

Error 2: Quando o sinalizador "Ignorar identificadores" for FALSE, "Ignorar literais" é VERDADEIRO e "Ignorar Anotações" é VERDADEIRO, a ferramenta mostrar a seguinte mensagem:
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at net.sourceforge.pmd.cpd.SourceCode.getSlice(SourceCode.java:173)
	at net.sourceforge.pmd.cpd.MatchAlgorithm.findMatches(MatchAlgorithm.java:83)
	at net.sourceforge.pmd.cpd.CPD.go(CPD.java:50)
	at net.sourceforge.pmd.cpd.GUI.go(GUI.java:631)
	at net.sourceforge.pmd.cpd.GUI.access$500(GUI.java:70)
	at net.sourceforge.pmd.cpd.GUI$GoListener$1.run(GUI.java:198)
	at java.lang.Thread.run(Unknown Source)

To try fix this last error, I also runned the version 5.5.2 with this parameters: "-Xmx4g -XX:-UseGCOverheadLimit", "-Xmx6g -XX:-UseGCOverheadLimit". But this not works.

In all executions, I used "Scan Subdirectories=TRUE" and "Duplicate chunks=75" and "File Encoding=UTF-8".

My Java version: 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

The source code that I analysed is Lucene (http://lucene.apache.org/solr/)

**Comment by jsotuyod** [comment] 2017-01-11 13:24
Thanks for the report. 

As for the null pointer, this seems a duplicate of https://sourceforge.net/p/pmd/bugs/1542/ which is fixed and will be included in pmd 5.5.3 and 5.6.0.

As for the out of memory, I will investigate what else changed to trigger that.

**Comment by jsotuyod** [comment] 2017-01-17 15:43
I confirm the NPE **is not** a duplicate, but a different case. I already have a fix locally.

I'm checking the OOM at the moment, will submit a PR soon.

**Comment by jsotuyod** [comment] 2017-01-18 19:02
As for the OOM, the problem is the sheer number of duplicate code violations being found on Lucene's source code when using ignore literals.

With 6GB of Heap Space, current PMD versions are able to find over 37500 instances of duplicate code of length 75+.

Even after doing some things to improve allocations / GC, this is simply too much to keep in memory. We will have to refactor our grouping stage code to report and discard matches on to go, rather than passing them all at once.

**Comment by jsotuyod** [comment] 2017-01-18 20:50
I did some improvements to the codebase, and CPD is now able to analyze the lucene source code given a sufficiently large heap (~7-8G) even when using `--ignore-literals`.

Bare in mind that `--ignore-literals` may not be the best option when analyzing Lucene. The source code has plenty of large arrays of strings (words in different languages), which to CPD this is just a sequence of N string literals, and being ignored, duplicate code to be removed; and is therefore currently producing a plain text report of over 800MB (much larger as XML). Such arrays should probably either be ignored by CPD (see [CPD Suppression](https://pmd.github.io/pmd-5.5.2/usage/cpd-usage.html#Suppression)), or moved out of the Java code into resource files loaded at runtime.

Still a complete rewrite of the CPD renderers is needed. Rendering to a String in memory is unsustainable. Once that's done the needed memory for analysis will drop dramatically.

**Comment by adangel** [comment] 2017-01-27 10:17
I've split this bug ticket into two - since the NPE is only for 5.5.3, while the OOM is for 5.4.4.

**Comment by adangel** [comment] 2017-01-27 10:51
The NPE bug is fixed for PMD 5.5.3 and later.
Thanks for reporting!

**Closed by adangel** 2017-01-27 10:51 UTC
Labels: bug
