### ISSUE TITLE
[ruby] CPD throwing java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by thiagoluizalves** [pmd/pmd#4040] opened 2022-07-11 19:23 UTC
**Affects PMD Version: 6.47.0, 6.46.0** 

**Description:**

Trying to run CPD against .rb files

**Exception Stacktrace:**

```
java.lang.IndexOutOfBoundsException: toIndex = 221
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1108)
	at net.sourceforge.pmd.cpd.SourceCode$CodeLoader.getCodeSlice(SourceCode.java:48)
	at net.sourceforge.pmd.cpd.SourceCode.getSlice(SourceCode.java:213)
	at net.sourceforge.pmd.cpd.Mark.getSourceCodeSlice(Mark.java:65)
	at net.sourceforge.pmd.cpd.Match.getSourceCodeSlice(Match.java:78)
	at net.sourceforge.pmd.cpd.SimpleRenderer.renderOn(SimpleRenderer.java:49)
	at net.sourceforge.pmd.cpd.SimpleRenderer.render(SimpleRenderer.java:87)
	at net.sourceforge.pmd.cpd.CPD.runCpd(CPD.java:214)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:185)
Jul 11, 2022 3:54:38 PM net.sourceforge.pmd.cpd.CPD runCpd
```

**Running PMD through:** *CLI*

**Comment by adangel** [comment] 2022-07-29 14:16
@thiagoluizalves Thanks for reporting this bug. However, I can't reproduce it. Can you give more information? What files did you analyze exactly? Are you using Linux, Windows or MacOSX (line ending can make a difference)? Which Java version are you using? What is the exact command line you used to run CPD?

**Comment by adangel** [comment] 2023-01-24 07:31
Closing this as not reproducible. If you have more information, feel free to comment.

**Closed by adangel** 2023-01-24 07:31 UTC
Labels: a:bug, in:cpd, was:unreproducible, needs-user-input
