### ISSUE TITLE
[java] UseUtilityClass  does not consider @UtilityClass  from lombok

### ISSUE THREAD

**Issue by deepak-patra** [pmd/pmd#1839] opened 2019-05-22 06:24 UTC
**Affects PMD Version: 6.13.0** 

**Rule: UseUtilityClass**

Description: All methods are static. Consider using a utility class instead. 

In code I have used @UtilityClass but PMD shows error for it. If I add a private constructor the error goes off.

**Comment by jsotuyod** [comment] 2019-05-22 13:33
@deepak-patra thanks for the report. However, this is a duplicate of #1094, so I'm merging this issue onto that one.

**Closed by jsotuyod** 2019-05-22 13:33 UTC
