### ISSUE TITLE
[apex] AvoidDirectAccessTriggerMap violation from normal Apex Class

### ISSUE THREAD

**Issue by parksungrin** [pmd/pmd#769] opened 2017-11-30 09:18 UTC
Please, prefix the report title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

**Rule Set:**
AvoidDirectAccessTriggerMap

**Description:**
AvoidDirectAccessTriggerMap violation is encountered from the Apex class when split string and access using index such as below.
   dummy_id_list.add(image_src.split('/')[5]);

**Code Sample demonstrating the issue:**
dummy_id_list.add(image_src.split('/')[5]);

Avoid directly accessing Trigger.old and Trigger.new
```

```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

**Comment by up2go-rsoesemann** [comment] 2017-11-30 23:43
@JAertgeerts didn't you add this rule?

**Comment by up2go-rsoesemann** [comment] 2018-01-03 15:05
@jsotuyod Isn't this a duplicate of #792 and fixed by my related PR?

**Comment by jsotuyod** [comment] 2018-01-04 04:14
@up2go-rsoesemann you are absolutely right, thanks!

**Closed by jsotuyod** 2018-01-04 04:14 UTC
Labels: a:false-positive
