### ISSUE TITLE
[xml] jaxen xpath function text() does not return an result for a rule

### ISSUE THREAD

**Issue by tkleiber** [pmd/pmd#915] opened 2018-02-16 11:51 UTC
**Affects PMD Version:** 
5.8.1, maybe higher versions

**Rule:** `/deployment-plan/application-name[text()[1]="app"]`

**Description:**

**Code Sample demonstrating the issue:** See uploaded test case

**Running PMD through:** *Ant*

[jaxen_xpath.zip](https://github.com/pmd/pmd/files/1731192/jaxen_xpath.zip)

**Comment by oowekyala** [comment] 2018-02-16 13:48
You can use `/deployment-plan/application-name/text[@Image="app"]` as a workaround. In the future, please don't upload an archive if your issue is reproducible in the designer

I don't know why the text() method doesn't work but I can imagine why it wouldn't be available for custom document models (our `Node`s). We could implement it ourselves as a custom function. 

On another note, the designer could really be improved to display XML ASTs more elegantly, it's currently a mess (eg displaying text nodes with line breaks specially). This could be part of the GSoC project. One downfall of wrapping DOM nodes is also that line numbers are inaccessible... which makes XPath rule design in the designer a bit harder.

**Comment by tkleiber** [comment] 2018-02-16 14:12
Have tested the workaround successfully. Doesn't know that the designer now supports xpath rules for xml, is there a link to some documentation?

**Comment by jsotuyod** [comment] 2018-02-16 14:22
@tkleiber the designer has been revamped in PMD 6.0.0. The new designer:

* is more friendly
* has more info
* supports all supported languages

![image](https://user-images.githubusercontent.com/802626/36311791-2caa15c0-130b-11e8-85bc-20927e25e9fa.png)

We have proposed a project for Google Summer of Code 2018 (we have recently been approved!) to further refine the new designer as per #714

**Comment by oowekyala** [comment] 2018-02-16 14:48
It's got pretty colors too !

**Comment by tkleiber** [comment] 2018-02-20 09:11
Seems that the workaround does not work in the designer too, or do I miss some button to execute teh xpath on windows?

![20180220_100826](https://user-images.githubusercontent.com/2185441/36415478-edbe9956-161d-11e8-9530-c5353bf14b58.png)

**Comment by oowekyala** [comment] 2018-02-20 10:08
For other languages, clicking on the match result highlights the node in the editor. XML doesn't support this well, since we use a DOM as an AST, which doesn't preserve line numbers. Hopefully it will be improved in the summer of code project

The XPath version that's run is chosen in the choicebox right next to the language choicebox. For a rule, it's the `version` property, which you can set to "1.0", or "2.0". If the workaround doesn't work in the designer, it's probable that it won't work as a standalone rule either, because the XPath expression of the designer is run exactly as if it were a rule

The workaround doesn't work in the current released version of the designer with XPath 2.0 because of #739. If when clicking a node in the AST all attributes have the value `null`, then that's certainly it. That issue is already fixed on master, but if you want to stick to a released version, you'll have to use XPath 1.0

**Comment by oowekyala** [comment] 2018-02-20 10:12
Thanks for you feedback btw, it's essential for us to have your impressions about eg the usage of the buttons, so that it can be improved. I agree clicking "Refresh AST" to refresh results feels weird, and we probably will replace that behaviour with auto-refresh of AST and XPath results -> #714

**Comment by jsotuyod** [comment] 2018-02-20 14:02
@tkleiber by default all rules use XPath 1.0, unless you specify other way by setting the rule's property `version`.

ie, to use XPath 2.0
 
```xml
<property name="version" value="2.0"/>
```

**Closed** 2022-03-25 07:24 UTC
Labels: a:bug, was:wontfix, in:xpath

**Comment by adangel** [comment] 2022-03-25 08:11
> won't fix, as the issue is Jaxen-specific. 6.44.0 adds a solution which only supports XPath 2. See #3864
