### ISSUE TITLE
[apex] syntax error on TYPEOF clauses in SOQL Queries

### ISSUE THREAD

**Issue by codefriar** [pmd/pmd#5054] opened 2024-06-05 21:01 UTC
**Affects PMD Version:** 
7.0.0 - 7.2.0

**Description:**

The following SOQL query snippet is valid, and deploys without issue:

```
(
                        SELECT
                            CreatedDate,
                            Id,
                            ParentId,
                            RecordTypeId,
                            OwnerId,
                            TYPEOF Owner
                                WHEN User THEN Name, Division // this is line 440.
                                WHEN Group THEN DeveloperName
                            END
                        FROM Cases
                    ), // For reference, this is line 444. 
``` 

However, when scanning it with pmd 7, the following  is logged:

```
[TRACE] Processing file (lang: apex+version:60): /Users/kevinpoorman/src/<PROJECT>/MyClass.cls
line 440:32 missing 'from' at 'WHEN'
Processing files  45% [===============================================================================================================================                                                                                                                                                      ] 1098/2394 (0:00:29) Violations:7603, Errors:0
line 440:42 missing ')' at 'THEN'
[INFO] Syntax error at 440:42: missing ')' at 'THEN'
line 440:47 missing 'from' at 'Name'
[INFO] Syntax error at 440:47: missing 'from' at 'Name'
line 441:43 no viable alternative at input 'Group THEN'
[INFO] Syntax error at 441:43: no viable alternative at input 'Group THEN'
line 441:48 missing ';' at 'DeveloperName'
[INFO] Syntax error at 441:48: missing ';' at 'DeveloperName'
line 443:24 missing ';' at 'FROM'
[INFO] Syntax error at 443:24: missing ';' at 'FROM'
line 444:20 mismatched input ')' expecting {'after', 'before', 'get', 'inherited', 'instanceof', 'set', 'sharing', 'switch', 'transient', 'trigger', 'when', 'with', 'without', 'system', 'user', 'select', 'count', 'from', 'as', 'using', 'scope', 'where', 'order', 'by', 'limit', 'and', 'or', 'not', 'avg', 'count_distinct', 'min', 'max', 'sum', 'typeof', 'end', 'then', 'like', 'in', 'includes', 'excludes', 'asc', 'desc', 'nulls', 'first', 'last', 'group', 'all', 'rows', 'view', 'having', 'rollup', 'tolabel', 'offset', 'data', 'category', 'at', 'above', 'below', 'above_or_below', 'security_enforced', 'system_mode', 'user_mode', 'reference', 'cube', 'format', 'tracking', 'viewstat', 'custom', 'standard', 'distance', 'geolocation', 'calendar_month', 'calendar_quarter', 'calendar_year', 'day_in_month', 'day_in_week', 'day_in_year', 'day_only', 'fiscal_month', 'fiscal_quarter', 'fiscal_year', 'hour_in_day', 'week_in_month', 'week_in_year', 'converttimezone', 'yesterday', 'today', 'tomorrow', 'last_week', 'this_week', 'next_week', 'last_month', 'this_month', 'next_month', 'last_90_days', 'next_90_days', 'last_n_days', 'next_n_days', 'n_days_ago', 'next_n_weeks', 'last_n_weeks', 'n_weeks_ago', 'next_n_months', 'last_n_months', 'n_months_ago', 'this_quarter', 'last_quarter', 'next_quarter', 'next_n_quarters', 'last_n_quarters', 'n_quarters_ago', 'this_year', 'last_year', 'next_year', 'next_n_years', 'last_n_years', 'n_years_ago', 'this_fiscal_quarter', 'last_fiscal_quarter', 'next_fiscal_quarter', 'next_n_fiscal_quarters', 'last_n_fiscal_quarters', 'n_fiscal_quarters_ago', 'this_fiscal_year', 'last_fiscal_year', 'next_fiscal_year', 'next_n_fiscal_years', 'last_n_fiscal_years', 'n_fiscal_years_ago', IntegralCurrencyLiteral
```

It seems like the underlying Apex parser has an issue with this (valid) syntax. it's causing pmd to throw an error.

**Exception Stacktrace:**

** No stacktrace, per-say is given **

**Code Sample demonstrating the issue:**

```apex
List<Case> scope = [
                SELECT
                    CreatedDate,
                    Id,
                    ParentId,
                    RecordTypeId,
                    OwnerId,
                    TYPEOF Owner
                        WHEN User THEN Name, Division
                        WHEN Group THEN DeveloperName
                    END,
                    (
                        SELECT
                            CreatedDate,
                            Id,
                            ParentId,
                            RecordTypeId,
                            OwnerId,
                            TYPEOF Owner
                                WHEN User THEN Name, Division
                                WHEN Group THEN DeveloperName
                            END
                        FROM Cases
                    )
                FROM Case
                WHERE
                    RecordType.DeveloperName = 'FOO'
                    OR RecordType.DeveloperName = 'BAR'
                ORDER BY CreatedDate ASC
            ];
```

**Steps to reproduce:**

1. Place the above query in a valid apex class.
2. make sure all the fields referenced exist in your org. 
3.  run PMD on this file.

**Running PMD through:** 

1. The CLI primarily. Specifically using this command line: `pmd check -R pmd/ruleset.xml -d force-app/main/default/classes -r pmd.csv --verbose`

**Comment by adangel** [comment] 2024-06-06 13:55
Thanks for reporting. This is a duplicate of #4922 .

**Closed by adangel** 2024-06-06 13:55 UTC
Labels: a:bug, was:duplicate
