### ISSUE TITLE
[apex] Stackoverflow when running PMD 6.38 on Apex code

### ISSUE THREAD

**Issue by rsoesemann** [pmd/pmd#3617] opened 2021-11-12 16:05 UTC
**Affects PMD Version:** 

Make sure, to test with the latest PMD version.

**Description:**

This is a hard to reproduce issue that only certain of our customers see with PMD 6.38. They check those rules on Apex classes 

> ApexBadCrypto, ApexCRUDViolation, ApexDangerousMethods, EmptyIfStmt, EmptyWhileStmt,ApexOpenRedirect, UnusedLocalVariable, OperationWithLimitsInLoop, ExcessiveClassLength, CyclomaticComplexity, IfStmtsMustUseBraces

and sometimes the run into those endless loops. As we cannot reproduce it locally and also cannot ask our customers to find out the minimal rule + files input we need to better understand why or when PMD or the Apex Parser could run into such a loop.

**Exception Stacktrace:**

```
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at copado.App.processRequest(App.java:179)
	at copado.App.main(App.java:104)
Caused by: java.lang.StackOverflowError: null
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.createNodeAdapter(ApexTreeBuilder.java:275)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.build(ApexTreeBuilder.java:285)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:437)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:480)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:127)
	at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:89)
	at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:90)

    Repeat 10 times

	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.build(ApexTreeBuilder.java:298)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:437)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:480)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:127)
	at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:89)
	at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:90)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.build(ApexTreeBuilder.java:298)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:437)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:480)
	at net.sourceforge.pmd.lang.apex.ast.ApexTreeBuilder.visit(ApexTreeBuilder.java:127)
	at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:89)
	at apex.jorje.semantic.ast.expression.BinaryExpression.traverse(BinaryExpression.java:90)
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

We currently cannot reproduce this locally and it also doesn't happen in all situations. It seems to be dependent on the code we give to PMD.

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

PMD 6.38 called from within a Closed Source DevOps Product called Copado

**Comment by oowekyala** [comment] 2021-11-14 00:24
This is a problem in the parser and we won't be able to investigate it without a source code example. Please find a way to create an MWE with code that is anonymised. From this stack trace, it looks like this has to do with binary expressions. IIRC each operator correspond to one level in the tree, so that may create very deep trees if you have eg a long string concatenation.

For instance if you write `"a" + "b" + "c"`, the tree has 3 levels, if you write `"a0" + "a1" + ... "an"`, then the tree has n levels. It's not hard in this way to create a tree that is too deep for recursive exploration, but long enough concatenation are usually only generated code. Maybe there's something like that in the relevant source files?

**Comment by adangel** [comment] 2021-11-14 18:43
With the regression tester, we sometimes have a similar problem - especially with the file [InputDetailASTJustToMakeStackoverflowError.java](https://github.com/checkstyle/checkstyle/blob/checkstyle-8.10/src/test/resources/com/puppycrawl/tools/checkstyle/api/detailast/InputDetailASTJustToMakeStackoverflowError.java).

Therefore we introduced a special (undocumented) property. If it is set (like it is done in [regression tester](https://github.com/pmd/pmd-regression-tester/blob/eb07344305237ec3291b5440a5c1a11cb9b5c019/lib/pmdtester/builders/pmd_report_builder.rb#L98)), PMD will catch such errors and turn them into processing errors, so that the problematic file appears in the report and PMD goes on. Since we would catch a Java VM stackoverflow error, it is not guaranteed, that PMD can go on (especially, as in the stacktrace foreign code - "jorje" is visible, so we don't know what happens - catching StackOverflow should only be done, if you know the code that is executed and you know, that the global static state is still consistent afterwards...).

Anyway, you can try to do the same here: Run PMD with `PMD_JAVA_OPTS="-Dpmd.error_recovery"` and see, if this yields any results...

**Comment by rsoesemann** [comment] 2021-11-17 20:22
We reported this back to the customer. I leave this open until we have an example to document here when such issues happen. Thanks for the ideas so far.

**Comment by adangel** [comment] 2021-11-18 07:50
One other thing to try: PMD 6.40.0 uses a new version or jorje, so maybe the error is gone with the latest PMD version?

**Comment by adangel** [comment] 2024-02-29 10:36
Since we switched away from Jorje with PMD 7.0.0 (see #3766 ), this might or might not be solved. The stacktrace is from Jorje and won't help with the new parser.

Since we don't have a reproducer, I'm closing this issue now.

**Closed by adangel** 2024-02-29 10:36 UTC
Labels: a:bug, was:unreproducible
