### ISSUE TITLE
[java] Never assign null to Optional variable.

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2046] opened 2019-10-01 13:36 UTC
**Affects PMD Version:** 
All.

**Rule:**
NullAssignmentToOptional.

**Description:**
Never assign null to an Optional variable. New rule needed.

**Code Sample demonstrating the issue:**

```
public Optional<Cart> fetchCart() {
    Optional<Cart> emptyCart = null;
    
}
```

**Running PMD through:**
Any.

References:
https://dzone.com/articles/using-optional-correctly-is-not-optional

**Comment by jsotuyod** [comment] 2019-10-01 13:42
Thanks for the suggestion, but this is a duplicate of #1034

**Closed by jsotuyod** 2019-10-01 13:42 UTC
Labels: was:duplicate
