### ISSUE TITLE
PMD user group to be created on Google groups

### ISSUE THREAD

**Issue by Fernal73** [pmd/pmd#2254] opened 2020-01-25 23:23 UTC
https://github.com/pmd/pmd/issues/2238#issuecomment-578415841

PMD needs  a Google group to address user issues directly. I recognize that it is an additional channel but at the same time I don't see it as a lot of additional work.
It also mitigates against the possibility that issues will be lost since anyone who posts to this group is genuinely seeking help, and not trying to gather points on StackOverflow.

I don't see SourceForge very useful for the above purpose in its current state.

**Comment by adangel** [comment] 2020-01-26 18:29
Let's rephrase that and look at the problem, rather the solution. You are providing a solution (Google Groups) without looking at the problem.

The problem as you say is: If PMD user has a questions (like "How do I?", "Why is that code problematic?", ...), then it is unclear, where to ask the question? Is that summary correct for the problem, you are trying to tackle?

Then I have to say, we already have this solved:

Quoting https://pmd.github.io/#support:

> Need help?
> * Look for common question on [StackOverflow](https://stackoverflow.com/questions/tagged/pmd)
> * Ask questions in the [Forum](https://sourceforge.net/p/pmd/discussion/)
> * or join the [Mailing List](https://lists.sourceforge.net/lists/listinfo/pmd-devel)
> * Found a bug? [Bug tracker](https://github.com/pmd/pmd/issues)
> * Source Code: [Check it out on github](https://github.com/pmd/pmd)

Btw - #2249 is exactly about this piece of information, which might be worth to be updated.

Since the problem is solved already, this can't be your real problem. Then your real problem is maybe this "I don't see SourceForge very useful for the above purpose in its current state." - But you just say, sourceforge sucks and you don't say, what the actual problem is.

Feel free to create a google group if you want - I won't create it.
Therefore I close this issue as invalid. Please don't waste our time anymore. Thanks.

**Closed by adangel** 2020-01-26 18:29 UTC
Labels: was:invalid
