### ISSUE TITLE
[core] Report unused violation suppression comments/annotations

### ISSUE THREAD

**Issue by oowekyala** [pmd/pmd#2074] opened 2019-10-16 15:20 UTC
From #2055 :

 > We currently report about suppressed violations, but we don't report about "unused suppression markers"

>  More generally, it would be nice to have a rule to detect unused `@SuppressWarnings`. Eg a `@SuppressWarnings("unchecked")` when a compiler wouldn't report any unchecked warning anyway.

> I was thinking, whether this could be part of this ViolationSuppressor interface? Something like `getAllSuppressionMarkers()` for a file. So that this functionality needs to be provided as part of the language implementation. We would then somehow figure out afterwards, which of the markers have been used...

**Comment by jsotuyod** [comment] 2020-05-14 16:08
This is actually a duplicate of #648, I'm adding that one to 7.0.0 milestone and merging there.

**Closed by jsotuyod** 2020-05-14 16:08 UTC
