### ISSUE TITLE
Maven multi module projects cause analysis cache to leak some resource

### ISSUE THREAD

**Issue by blackmamo** [pmd/pmd#1273] opened 2018-08-01 12:55 UTC
**Affects PMD Version:** *[6.0.1]* 

**Rule:** *[N/A]*

**Description:** *In a maven aggregate project with multiple children, using the pmd plugin with the analysis cache enabled, there appears to be some sort of leak. You see logs like, below. The first child built has just one log line, the second 2 & so on until you end up with beasts like this:

[INFO] --- maven-pmd-plugin:3.9.0:pmd (pmd) @ embonds.utils ---
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, rulesets changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache invalidated, execution classpath changed.
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
[INFO] Analysis cache updated
*

**Code Sample demonstrating the issue:**

```

```

**Running PMD through:** *[Maven]*

**Comment by adangel** [comment] 2018-08-01 15:12
Hi, this is already fixed with a newer version of the maven-pmd-plugin. The issue is described here: https://issues.apache.org/jira/browse/MPMD-258

Please update to maven-pmd-plugin 3.10.0.

**Closed by adangel** 2018-08-01 15:12 UTC
