### ISSUE TITLE
[core] Version 5.5.4 seems to hold file lock on rules JAR (affects Windows only)

### ISSUE THREAD

**Issue by sschuberth** [pmd/pmd#337] opened 2017-04-11 15:23 UTC
**Rule Set:**

See https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/PmdPluginAuxclasspathIntegrationTest.groovy#L108

**Description:**

After running PMD via the Gradle plugin, the `pmd-rule.jar` cannot deleted anymore on Windows, apparently because some file lock is held. Works with version 5.5.3, does not work with version 5.5.4. Discovered when trying to upgrade the PDM version the Gradle plugin uses, see https://github.com/gradle/gradle/pull/1623#issuecomment-293234259.

**Code Sample demonstrating the issue:**

1. Clone https://github.com/sschuberth/gradle
2. Checkout the *pmd-upgrade* branch
3. Run `./gradlew codeQuality:integTest --tests org.gradle.api.plugins.quality.PmdPluginAuxclasspathIntegrationTest`

**Running PMD through:** *Gradle*

**Comment by jsotuyod** [comment] 2017-04-11 16:13
Mmmm... that's interesting.... I don't recall us modifying anything even remotely related to this... and specially not something that would only affect a single platform... I'll investigate

**Comment by sschuberth** [comment] 2017-04-11 16:25
Well, it is probably Windows specific because on Windows you cannot delete locked files, whereas on Linux you can. I mean, I don't expect any explicitly platform specific code to be the culprit.

**Comment by jsotuyod** [comment] 2017-04-11 16:34
I just went over every single commit from PMD 5.5.4 to PMD 5.5.5. most of them are either Apex specific or related to automatic builds on Travis (bash scripts, Travis config). The rest either edit specific Java rules, or a single one, alters Symbol Table analysis. No changes were introduced to the core module.

So far I see no reason for the regression....

**Comment by ryan-gustafson** [comment] 2017-04-11 18:05
I wonder if this could help track it down:
http://file-leak-detector.kohsuke.org/

**Comment by jsotuyod** [comment] 2017-04-11 18:17
The only related change on recent history is fixing #234 (see pr #235), but that fix was part of both 5.5.4 and, of course, 5.5.5...

**Comment by sschuberth** [comment] 2017-04-11 18:47
@jsotuyod But then that *could* be the issue, as version 5.5.**3** works for me, while version 5.5.4 and above do not.

**Comment by jsotuyod** [comment] 2017-04-11 18:59
@sschuberth sorry, you are right. I got a little dizzy.

I see nothing wrong with #235 'though...

**Comment by ryan-gustafson** [comment] 2017-04-11 19:31
https://github.com/pmd/pmd/pull/235 changed from using URLClassLoader.getResourceAsStream which closed InputStreams when the ClassLoader was closed, to independently opening URLs and no longer relying on the URLClassLoader to manage the InputStreams.  The original version could have allowed users of the InputStreams to be sloppy, but what if now they are not all closing the InputStreams?

Again, consider trying to track down the resources using the above tool.  I've not personally used it, but it may point clearly at the issue?

**Comment by jsotuyod** [comment] 2017-04-11 19:43
@ryan-gustafson that's actually a very good point.

**Comment by ryan-gustafson** [comment] 2017-04-11 20:11
@sschuberth Anything calling ResourceLoader.loadResourceAsStream and hit this section: https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/util/ResourceLoader.java#L95

Not sure what exactly that is, would need to dig through the code, which isn't on my short term list of things to do at the moment.  I just chimed in because I was randomly browsing recent items in my pmd-devel inbox and thought maybe I could help. :)

Hopefully there's an internal candidate in PMD, but worse case it's somebody on the outside.  This is a `public` API method unfortunately.

If I get through my tasks today, I might try to see if I can debug it this evening, if someone else hasn't already.

**Comment by jsotuyod** [comment] 2017-04-11 20:13
@sschuberth within PMD itself. Gradle just launches the PMD ant task.

@ryan-gustafson the tool is only showing leaks caused by the JRE itself:

```
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1045)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at net.sourceforge.pmd.lang.LanguageRegistry.<init>(LanguageRegistry.java:30)
```

Couriously, these are closed according to the source (Oracle JRE 8, ServiceLoader.parse, line 312-313).

I sporadically also get a reported leaked handle on [PMD.java](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/PMD.java#L580-L590), but as seen on the code, the stream is actually closed...

I guess I don't really trust that tool... Your input however may actually point us in the right direction.

**Comment by sschuberth** [comment] 2017-04-11 20:14
Thanks @jsotuyod. At least I just checked that no code in the Gradle repo is calling `loadResourceAsStream` directly.

**Comment by sschuberth** [comment] 2017-04-11 20:20
> @sschuberth within PMD itself.

Doesn't this line look suspicious then?

https://github.com/pmd/pmd/blob/daf560a0bd0be14243b9bf0792babcade5039f1d/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java#L123

**Comment by jsotuyod** [comment] 2017-04-11 20:21
@sschuberth yes, that's one of the lines I'm looking into.

**Comment by ryan-gustafson** [comment] 2017-04-11 20:26
A local hack would be to track the closables like the old classloader used to, as well as capture a stacktrace on allocation.  Then on JVM shutdown (?) log the traces to see who was allocating but not closing.

Generalizing slightly, you could wrap any Closable resource into a tracker to facilitate leak diagnostics.

**Comment by adangel** [comment] 2017-04-11 20:30
@sschuberth @jsotuyod 
I've ran the tool via `JAVA_OPTS=-javaagent:file-leak-detector-1.8-jar-with-dependencies.jar=trace=filehandles-trace.txt`. However, in the filehandles-trace.txt file, no `pmd-rule.jar` is mentioned. Is gradle executing the test in a separate JVM maybe?

Looking at the content of pmd-rule.jar: It contains a ruleset with one rule and the rule class itself. As far as I see, we [load the ruleset via a try-with-resources](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java#L272) and then [load/instantiate the class](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java#L449). Could it be, that the JVM still holds a reference to the jar file, from which the class has been constructed?

The line in RuleSetFactory mentioned above is definitively a leak - however, it seems to be only triggered by the "Benchmarking" functionality...

**Comment by ryan-gustafson** [comment] 2017-04-11 20:36
@adangel I wouldn't be surprised if the leaked InputStreams point directly to files inside the JAR, and each one separately opens the File.  Not closing them would have the same effect on the .jar file as the ClassLoader, if it were still open.  For example:

`jar:package.zip!path/to/the/file`

I'd start by closing all the streams first.

**Comment by jsotuyod** [comment] 2017-04-11 20:37
> A local hack would be to track the closables like the old classloader used to, as well as capture a stacktrace on allocation. Then on JVM shutdown (?) log the traces to see who was allocating but not closing.

Hacky, but may work. I'll may try it if I find myself the time.

> @sschuberth @jsotuyod
I've ran the tool via JAVA_OPTS=-javaagent:file-leak-detector-1.8-jar-with-dependencies.jar=trace=filehandles-trace.txt. However, in the filehandles-trace.txt file, no pmd-rule.jar is mentioned. Is gradle executing the test in a separate JVM maybe?

Maybe... you could just create the **real** dummy project and run gradle on it manually.

> Looking at the content of pmd-rule.jar: It contains a ruleset with one rule and the rule class itself. As far as I see, we load the ruleset via a try-with-resources and then load/instantiate the class. Could it be, that the JVM still holds a reference to the jar file, from which the class has been constructed?

Shouldn't. Upon closing a URLClassLoader (since Java 7) no more instances of the class can be generated, even if there are existing instances in memory; and the jar is effectively closed and ready to be deleted if needed. You can check more info here: http://docs.oracle.com/javase/7/docs/technotes/guides/net/ClassLoader.html

> The line in RuleSetFactory mentioned above is definitively a leak - however, it seems to be only triggered by the "Benchmarking" functionality...

... and when referencing a properties file that is not even present on that test scenario.
I've fixed it locally non the less.

**Comment by ryan-gustafson** [comment] 2017-04-12 08:59
Looking at `URLClassLoader` closer, it seems that when opening from a JAR file, closing the `InputStream` is insufficient.  The `JarFile` on the `JarURLConnection` must also be closed.  Something like the following sufficed to get the **gradle** integration tests to work.

In figuring this out, I had close() tracking in place, and leaks were logged coming from `RuleSetFactoryTest` and `AbstractRuleSetFactoryTest`.  I didn't run everything or search all the code looking for more.  They are trivial to fix with the try-resource construct.

Anyway, this is the modified snippet I used within `ResourceLoader.loadResourceAsStream`.  I won't be able to get to submitting a PR for a while, feel free to run with this.
```
                try {
                    /*
                     * Don't use getResourceAsStream to void reusing connections between threads
                     * See https://github.com/pmd/pmd/issues/234
                     */
                    URL resource = loader.getResource(name);
                    if (resource == null) {
                        // Don't throw RuleSetNotFoundException, keep API compatibility
                        return null;
                    }
                    final URLConnection connection = resource.openConnection();
                    final Allocation allocation = new Allocation(resource, new Throwable());
                    final InputStream inputStream = connection.getInputStream();
                    // Wrap the InputStream to also close the underlying JarFile if from a JarURLConnection.
                    return new InputStream() {
                        @Override
                        public int read() throws IOException {
                            return inputStream.read();
                        }

                        @Override
                        public void close() throws IOException {
                            inputStream.close();
                            if (connection instanceof JarURLConnection) {
                                ((JarURLConnection) connection).getJarFile().close();
                            }
                        }
                    };
                } catch (IOException e1) {
                    // Ignored
                }
```

**Comment by sschuberth** [comment] 2017-04-12 09:18
Great stuff, @ryan-gustafson! I'll wait until this lands upstream before I submit this to Gradle.

**Closed** 2017-04-14 09:56 UTC
Labels: bug
