### ISSUE TITLE
[java] False positive JUnitTestContainsTooManyAsserts for JUnit 5 assertAll()

### ISSUE THREAD

**Issue by christianhujer** [pmd/pmd#2374] opened 2020-03-20 19:19 UTC
**Affects PMD Version:** 6.22.0

**Rule:** JUnitTestContainsTooManyAsserts

**Description:**
When `Assertions.assertAll()` is used, that should be treated as a single assert.

**Code Sample demonstrating the issue:**

```
class SampleTest {
    @Test
    void sampleTestCase() {
        final Point input = new Point(1, 2);
        final Point result = p.add(p);
        assertAll(
            () -> assertEquals(2, result.x),
            () -> assertEquals(4, result.y),
        );
    }
}
```

**Running PMD through:** *Gradle*

**Comment by oowekyala** [comment] 2020-11-10 11:14
Duplicate of #1212

**Closed by oowekyala** 2020-11-10 11:14 UTC
