### ISSUE TITLE
[java] A false negative about UseStringBufferLength 

### ISSUE THREAD

**Issue by Zustin** [pmd/pmd#3453] opened 2021-08-09 02:45 UTC
**Affects PMD Version:6.35.0** 

**Rule:UseStringBufferLength**

Please provide the rule name and a link to the rule documentation:
https://pmd.github.io/pmd-6.36.0/pmd_rules_java_performance.html#usestringbufferlength

**Description:**
Hi, I found a false negative about the rule UseStringBufferLength. The minimal case is below. Considering this rule, variable str is a constant (final type), I think our tool should have reported a warning at line 4. Thanks. 

**Code Sample demonstrating the issue:**

```java
public void useStringBufferLength() {
   StringBuffer sb = new StringBuffer("Hello PMD!");
   final String str = "";
   sb.toString().equals(str); // should report a warning here
}
```

**Expected outcome: A warning based on this rule**

PMD should report a violation at line 4, but doesn't. This is a false-negative.

**Running PMD through:** *[Maven]*

**Comment by tweimer** [comment] 2021-12-10 13:26
Same as #3639

**Comment by adangel** [comment] 2022-01-20 15:13
Closing as duplicate of #3639

**Closed by adangel** 2022-01-20 15:13 UTC
Labels: was:duplicate
