### ISSUE TITLE
[java] Invalid UnnecessaryFullyQualifiedName on same name variable in same package

### ISSUE THREAD

**Issue by blacelle** [pmd/pmd#2018] opened 2019-09-16 15:28 UTC
**Affects PMD Version:** 
6.18.0

**Rule:**
UnnecessaryFullyQualifiedName 

**Description:**
We have 2 interfaces in the same package: A and B. A defines the contant CONSTANT, and B defines a constant with same name, referencing A.CONSTANT:

**Code Sample demonstrating the issue:**

```
package toto;
interface A {
 String CONSTANT = "youpi";
}

package toto;
interface B {
 String CONSTANT = A.CONSTANT;
}
```

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
maven

**Comment by blacelle** [comment] 2019-09-16 15:33
Just to confirm: my interfaces does not hold any import clause, while PMD indicates:

>  Unnecessary use of fully qualified name 'A.CONSTANT' due to existing same package import 'toto.*'.

**Comment by blacelle** [comment] 2019-09-16 15:37
Might be a duplicate of https://github.com/pmd/pmd/issues/2017#issuecomment-531578714

**Comment by Fernal73** [comment] 2019-09-20 00:05
I have a slew of errors of this kind in my projects now:

One example:

```java
package javapuzzles;

public enum Client {
  ;

  public static void main(String[] args) {
    System.out.println(Cache.getSum());
  }
}

@SuppressWarnings({"checkstyle:onetoplevelclass", "PMD"})
enum Cache {
  ;

  static {
    initializeIfNecessary();
  }

  private static int sum;

  public static int getSum() {
    initializeIfNecessary();
    return sum;
  }

  private static boolean initialized = false;

  private static synchronized void initializeIfNecessary() {
    if (!initialized) {
      for (int i = 0; i < 100; i++)
        sum += i;
      initialized = true;
    }
  }
}

**Comment by jsotuyod** [comment] 2019-09-22 20:37
Effectively a duplicate of #2017. Already fixed in master. Thanks for the report nonetheless.

**Closed by jsotuyod** 2019-09-22 20:37 UTC
