### ISSUE TITLE
[java] Linux found false-positive but windows pass

### ISSUE THREAD

**Issue by enexusde** [pmd/pmd#4126] opened 2022-09-13 09:21 UTC
**Affects PMD Version:** 

6.49.0

**Description:**

`mvn pmd:check` fails on linux only by a false-positive. Windows passes.

**Exception Stacktrace:**

No exception.

**Code Sample demonstrating the issue:**

```java
/*  ___     _
 * | _ \___| |___ __ _ ___ ___  Copyright 2016
 * |   / -_) / -_) _` (_-</ -_) https://www.e-nexus.de./
 * |_|_\___|_\___\__,_/__/\___| by Peter Rader   _
 * |  \/  |__ _ _ _  __ _ __ _ ___ _ __  ___ _ _| |_
 * | |\/| / _` | ' \/ _` / _` / -_) '  \/ -_) ' \  _|
 * |_|  |_\__,_|_||_\__,_\__, \___|_|_|_\___|_||_\__|
 * All rights reserved    |___/
 */
package de.e_nexus.web.rm.db.replic;

import javax.inject.Named;
import javax.transaction.Transactional;

import static de.e_nexus.web.rm.entity.SELECT.*; // Importing FROM and WHERE. It fails on linux only. Windows passes.
import de.e_nexus.web.rm.entity.SQLDatabase;
import de.e_nexus.web.rm.entity.SQLDatabaseTableType;

@Named
@Transactional
public class NextGenerationFieldModifier extends BaseFieldModifier {

	public void addAvailableTableType(final String typename, final long databaseId) {
		SQLDatabaseTableType tt = FROM(SQLDatabaseTableType.class).AS(TT -> WHERE(TT.typeName).ㅤᆖㅤ(typename).SELECT().ꁘ(TT))
				.first(em, () -> new SQLDatabaseTableType().setTypeName(typename));
		SQLDatabase db = em.find(SQLDatabase.class, databaseId);
		db.getExistingTableTypes().add(tt);
		em.persist(db);
	}
}
```

This is the `pmd.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd xmlns="http://pmd.sourceforge.net/report/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pmd.sourceforge.net/report/2.0.0 http://pmd.sourceforge.net/report_2_0_0.xsd" version="6.49.0" timestamp="2022-09-13T11:05:03.372">
<file name="/tmp/pmd/release-management/trunk/de.e_nexus.web.rm.db/src/main/java/de/e_nexus/web/rm/db/replic/NextGenerationFieldModifier.java">
<violation beginline="15" endline="15" begincolumn="1" endcolumn="48" rule="UnnecessaryImport" ruleset="Code Style" package="de.e_nexus.web.rm.db.replic" class="NextGenerationFieldModifier" externalInfoUrl="https://pmd.github.io/pmd-6.49.0/pmd_rules_java_codestyle.html#unnecessaryimport" priority="4">
Unused import 'de.e_nexus.web.rm.entity.SELECT.*'
</violation>
</file>
</pmd>
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1. Install windows and linux.
2. Install maven
3. execute mvn pmd:check on windows.
4. execute mvn pmd:check on linux.

**Running PMD through:**
Maven

Windows11, Linux Ubuntu 4.15.0-66-generic.
Maven version Windows: 3.8.5
Maven version Linux: 3.6.3

**Comment by jsotuyod** [comment] 2022-10-05 17:08
@enexusde am I right to assume that the classes under `de.e_nexus.web.rm.entity.SELECT.*` are part of the same codebase being analyzed?

If that's the case, this seems more like an issue on execution rather than PMD itself…

When Maven executes PMD, by default the [`typeResolution` flag](https://maven.apache.org/plugins/maven-pmd-plugin/pmd-mojo.html#typeResolution) is set to true. As you don't provide info on the pom configuration for the plugin, I'd assume it's not being overridden. This allows PMD to gather info both from dependencies and output directories (such as `target/classes`), which allows PMD to actually know what classes may be hidden under that `*` to be accurate on these detections. When the data is not available, PMD falls back to a best-effort approach, that will produce false positives such as the ones you report here.

Unfortunately, even when the flag is set, the `pmd:pmd` target doesn't actually depend on the `compile` / `testCompile` targets to ensure the classes are compiled and up to date (@adangel is this something that the plugin can actually improve on?). My guess here is that when you run this on Windows, the compiled classes were present under `target/classes`, but that was not the case under Linux.

If my theory is correct, `mvn clean pmd:check` should fail in both platforms, while doing `mvn compile pmd:check` (and/or `testCompile` if test sources are being analyzed) should work on both platforms.

**Comment by adangel** [comment] 2022-10-06 08:38
> Unfortunately, even when the flag is set, the pmd:pmd target doesn't actually depend on the compile / testCompile targets to ensure the classes are compiled and up to date (@adangel is this something that the plugin can actually improve on?).

Potentially. E.g. `pmd:check` already depends on `pmd:pmd` and calls this mojo before itself (https://maven.apache.org/plugins/maven-pmd-plugin/check-mojo.html -> "Invokes the execution of this plugin's goal pmd prior to executing itself."). Maybe it could be enhanced.

The default use case is actually, to use [lifecycles](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html). E.g. pmd:check by default binds to the `verify` lifecycle. This makes sure, that everything before has been properly executed before pmd is running (compile, test, ...). 

It is indeed as easy as changing an annotation, to make sure, another complete lifecycle is executed ("forked"). This is done in the "aggregate-pmd" goal (https://github.com/apache/maven-pmd-plugin/blob/1d1116efe4452bb047015486b635b900d8814ec1/src/main/java/org/apache/maven/plugins/pmd/AggregatorPmdReport.java#L35). But this is not what you always want - it would then fork *everytime* another lifecycle (AFAIK) leading to the situation, that the project is compiled twice, if it is build the "normal" way (`mvn clean verify`). For the aggregator report, the problem is described in https://maven.apache.org/plugins/maven-pmd-plugin/examples/aggregate.html - it's a problem for multi-module projects (aggregator builds).

But if such a feature (forking lifecycle) is wanted - please create an issue at https://issues.apache.org/jira/projects/MPMD/summary

**Comment by adangel** [comment] 2022-10-06 08:47
Oh - by the way: the maven-pmd-plugin should already issue a warning [The project xyz does not seem to be compiled. PMD results might be inaccurate](https://maven.apache.org/plugins/maven-pmd-plugin/faq.html#typeresolution_aggregate) when it sees, that `target/classes` is missing or empty...

**Comment by adangel** [comment] 2022-10-06 08:52
> It is not part of the same java-sourcecodebase. Although its part of the same java-bytecode-base (jar as maven dependency), it content is a dynamic maven artifact compiled at buildtime.

Do you mean by that, that `de.e_nexus.web.rm.entity.SELECT` is part of a separate maven module in the same aggregator?

E.g.

```
parent-aggregator-project
  |- module "db-lib" (contains de.e_nexus.web.rm.entity.SELECT)
  \ module "service"
```

Module "service" depends on module "db-lib".

On which level do you execute "pmd:check"? Maybe you need to call it on the parent project, so that first "db-lib" is build and afterwards "service"?

**Comment by adangel** [comment] 2023-01-24 07:29
Closing this as not reproducible. If you have more information on how to reproduce this problem, please comment.

**Closed by adangel** 2023-01-24 07:29 UTC
Labels: a:bug, was:unreproducible, needs-user-input
