### ISSUE TITLE
[java] PMD Processing Error caused by ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MPoorter** [pmd/pmd#3504] opened 2021-09-15 11:22 UTC
**Affects PMD Version: 6.38.0** 

**Description:**

We're running into a PMD processing error when doing an analysis of our codebase after upgrading to `maven-pmd-plugin` version 3.15.0, which uses PMD version 6.38.0. Running with the `-X` flag enabled, we can see the following stack trace.

**Exception Stacktrace:**

```
[ERROR] /Users/matt/IdeaProjects/uk-auto-test/uk-auto-test-service/src/main/java/com/marshmallow/uk_auto_test/service/impl/TestService.java: PMDException: Error while processing /Users/matt/IdeaProjects/uk-auto-test/uk-auto-test-service/src/main/java/com/marshmallow/uk_auto_test/service/impl/TestService.java
net.sourceforge.pmd.PMDException: Error while processing /Users/matt/IdeaProjects/uk-auto-test/uk-auto-test-service/src/main/java/com/marshmallow/uk_auto_test/service/impl/TestService.java
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:128)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:100)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:62)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:85)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:29)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 32860 out of bounds for length 16516
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(PMDASMClassLoader.java:118)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.populateClassName(ClassTypeResolver.java:1617)
        at net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(ClassTypeResolver.java:214)
        at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept(ASTCompilationUnit.java:44)
        at net.sourceforge.pmd.lang.java.typeresolution.TypeResolutionFacade.initializeWith(TypeResolutionFacade.java:21)
        at net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(AbstractJavaHandler.java:121)
        at net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(SourceCodeProcessor.java:178)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:205)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache(SourceCodeProcessor.java:118)
        ... 10 more

```

**Code Sample:**
If necessary I can provide this, but as it contains sensitive data, I wanted to see whether this provides enough information as is.

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  mvn clean verify pmd:aggregate-pmd-check

**Running PMD through:** *Maven*

AdoptOpenJDK: 15

**Comment by adrien-martin** [comment] 2021-11-30 16:13
Had the same problem.
`maven-pmd-plugin` seems to have an indirect dependency on `asm:asm:jar:3.3.1`, which is very old, and should now be `org.ow2.asm:asm`.
The last version of `asm` is `9.2`.

So i disabled this dependency for the plugin;
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.15.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.eclipse.sisu</groupId>
                        <artifactId>org.eclipse.sisu.plexus</artifactId>
                        <version>0.0.0.M2a</version>
                        <exclusions>
                            <exclusion>
                                <groupId>asm</groupId>
                                <artifactId>asm</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                </dependencies>
...
            </plugin>
```
I think it use and `asm.jar` provided by the maven installation.
If not present maybe a direct dependency with scope test must be added.
E.g. with Debian the `maven` package has a dependency on `libasm-java`, 9.1 for bullseye.

Here is the dependency graph i had with `mvn -X`:
```
[DEBUG] org.apache.maven.plugins:maven-pmd-plugin:jar:3.15.0
[DEBUG]    org.apache.maven:maven-core:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.1.0:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M2a:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]             javax.inject:javax.inject:jar:1:compile
[DEBUG]          com.google.guava:guava:jar:10.0.1:compile
[DEBUG]             com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]          org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[DEBUG]             aopalliance:aopalliance:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a:compile
[DEBUG]             asm:asm:jar:3.3.1:compile
```

**Comment by adangel** [comment] 2021-11-30 17:01
Thanks for the info. Then this is a duplicate of #3502 
See https://issues.apache.org/jira/browse/MPMD-325 for the fix on the m-pmd-p side.

**Comment by adrien-martin** [comment] 2021-12-01 09:03
Thanks for the link, it is indeed a `maven-pmd-plugin` bug.

Anyway adding an `org.ow2.asm:asm` dependency is a better workaround than altering the `org.eclipse.sisu.plexus` dependency.

**Comment by oowekyala** [comment] 2022-02-06 15:42
This appears to be fixed since the maven pmd plugin has been released with a fix: https://github.com/pmd/pmd/issues/3502#issuecomment-1030611178

**Closed by oowekyala** 2022-02-06 15:42 UTC
Labels: a:bug
