### ISSUE TITLE
[java] A checker that for unnecessary @SuppressWarnings("PMD.*")

### ISSUE THREAD

**Issue by boris-petrov** [pmd/pmd#1188] opened 2018-06-12 08:23 UTC
This is a feature request.

I have a bunch of `@SuppressWarnings("PMD.*")` suppressions (some of them because of PMD bugs) and with every new release I have to check if they are needed or not any more. Such a check would be nice.

**Comment by jsotuyod** [comment] 2018-06-12 19:47
@boris-petrov thanks for the suggestions. This is a duplicate of #648, I'll close this to keep tracking it there.

**Closed by jsotuyod** 2018-06-12 19:47 UTC
