### ISSUE TITLE
[java] Resolve dependencies of :pmd > Resolve dependencies of :detachedConfiguration78

### ISSUE THREAD

**Issue by nicoabie** [pmd/pmd#3134] opened 2021-02-24 00:59 UTC
**Affects PMD Version:** 
From 6.22.0 onwards

**Description:**

Everytime pmd is executed that dependency must be resolved and it takes 3mins

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*
gradle
jdk 11.0.2

**Comment by adangel** [comment] 2021-02-25 11:07
Thanks for the report. Can you give a bit more information on this issue? PMD uses maven as a build tool, so, I assume, you are using the gradle pmd plugin.

Gradle is developed over there -> https://github.com/gradle/gradle

If you can give us the information, which dependency is creating you difficulty, we can see, whether PMD brings in this dependency (then we can fix it here) or gradle (then it need to be fixed there).

A output from your build would also be helpful.

**Comment by nicoabie** [comment] 2021-02-25 12:25
Thanks for the quick response! The dependency that is bringing problems is detachedConfiguration78 I would try to post here the stack trace or some more info.

**Comment by adangel** [comment] 2021-03-04 14:48
Without more info, we can't help you.
Most important would be: Which version of gradle are you using? Did you try to use the latest gradle version?
Can you share your build.gradle files?
Which build plugins besides "pmd" are you using?
How many dependencies do you have?
Do you use subprojects?

About detachedConfiguration, I found these threads:
* https://discuss.gradle.org/t/what-is-detachedconfiguration-i-have-a-lots-of-them-for-each-subproject-and-resolving-them-takes-95-of-build-time/31595
* https://github.com/gradle/gradle/issues/5284

As far as I understand, detachedConfiguration has to do with temporary dependency resolution for tasks/extensions.
The PMD gradle plugin deals with two classpaths:
1. the classpath to execute PMD itself - configurable via `toolVersion` (https://github.com/gradle/gradle/blob/98a186f3ed7c4f629608d236ab31ddef442c9293/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java#L96-L103). This is named "pmdClasspath".
2. the classpath of the project, needed as auxiliary classpath, named "classpath" in gradle and "auxclasspath" in ant/PMD: https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java#L145-L151

I guess, at both places, dependency resolution could take place. The second usage uses you project's compile classpath, which means the classpath of your project is maybe once again resolved for PMD. If your dependency resolution anyway takes much time, then it will double if you add the PMD plugin, because then gradle does the same work twice (so far as I understand it. With a newer version of gradle, that could be already optimized).

**Comment by nicoabie** [comment] 2021-03-04 16:15
Thanks Andreas, as soon as I have time I would check on that, unfortunately I don't have build errors or a stack trace to share here but I will take the time to read those topics you provided!

**Comment by adangel** [comment] 2023-01-24 07:33
Closing this as not reproducible. If you have more information, feel free to comment.

**Closed by adangel** 2023-01-24 07:33 UTC
Labels: a:bug, was:unreproducible, needs-user-input
