### ISSUE TITLE
[java] NPE Exception applying rule SingularField on file

### ISSUE THREAD

**Issue by diziaq** [pmd/pmd#3303] opened 2021-05-25 18:35 UTC
**Affects PMD Version:** 

6.34.0 (maven-pmd-plugin:3.14.0)

**Description:**

Got NPE while PMD is trying to apply rule **SingularField** to a class with a method calling try-with-resources
where AutoCloseable parameter is a private (!) class field.

**Exception Stacktrace:**

```
[INFO] --- maven-pmd-plugin:3.14.0:pmd (pmd) @ core-receiver ---
[WARNING] Exception applying rule SingularField on file D:\FT\project\my_project\src\main\java\mypackage\Something.java, continuing with next rule
java.lang.NullPointerException
    at net.sourceforge.pmd.lang.java.rule.design.SingularFieldRule.visit (SingularFieldRule.java:149)
    at net.sourceforge.pmd.lang.java.ast.ASTFieldDeclaration.jjtAccept (ASTFieldDeclaration.java:59)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:220)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:267)
    at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBodyDeclaration.jjtAccept (ASTClassOrInterfaceBodyDeclaration.java:44)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:220)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:262)
    at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceBody.jjtAccept (ASTClassOrInterfaceBody.java:35)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:220)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:232)
    at net.sourceforge.pmd.lang.java.rule.AbstractLombokAwareRule.visit (AbstractLombokAwareRule.java:74)
    at net.sourceforge.pmd.lang.java.ast.ASTClassOrInterfaceDeclaration.jjtAccept (ASTClassOrInterfaceDeclaration.java:56)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:220)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:417)
    at net.sourceforge.pmd.lang.java.ast.ASTTypeDeclaration.jjtAccept (ASTTypeDeclaration.java:39)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:220)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:392)
    at net.sourceforge.pmd.lang.java.rule.AbstractLombokAwareRule.visit (AbstractLombokAwareRule.java:58)
    at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept (ASTCompilationUnit.java:44)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll (AbstractJavaRule.java:163)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply (AbstractJavaRule.java:157)
    at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply (AbstractDelegateRule.java:336)
    at net.sourceforge.pmd.RuleSet.apply (RuleSet.java:575)
    at net.sourceforge.pmd.RuleSets.apply (RuleSets.java:148)
    at net.sourceforge.pmd.SourceCodeProcessor.processSource (SourceCodeProcessor.java:194)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache (SourceCodeProcessor.java:107)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode (SourceCodeProcessor.java:89)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode (SourceCodeProcessor.java:51)
    at net.sourceforge.pmd.processor.PmdRunnable.call (PmdRunnable.java:78)
    at net.sourceforge.pmd.processor.PmdRunnable.call (PmdRunnable.java:24)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
[WARNING] PMD processing errors:
[WARNING] D:\FT\project\my_project\src\main\java\mypackage\Something.java: NullPointerException: null
```

**Code Sample demonstrating the issue:**

```java
// real analogues of such an overriding are javax.jms.JMSConsumer, javax.jms.JMSContext in JMS 2.0
interface NoThrowingCloseable extends AutoCloseable {
 @Override
  void close();
}

class Something {
  // "private" is a must for reproducing the problem
  private final NoThrowingCloseable first;

  Something(NoThrowingCloseable first) {
    this.first = first;
  }

  public void performClosing() {
    try (first) {
      // this block can be empty or not
    }
  }
}
```

**Steps to reproduce:**
1. Windows 10, Java 11.0.10, Maven 3.6.3
2. default configuration of maven-pmd-plugin:3.14.0 
3. call `mvn pmd:check` from command line

**Comment by oowekyala** [comment] 2021-06-23 21:34
This is actually a dup of #3006 and was fixed by #3070 in pmd 6.31.0

**Closed by oowekyala** 2021-06-23 21:34 UTC
Labels: a:bug

**Comment by oowekyala** [comment] 2021-06-23 21:37
err.. So the fix was merged in pmd 6.31.0, and I for sure can't reproduce this in master. @diziaq sorry for asking but is this really with pmd 6.34.0? I'm puzzled

**Comment by diziaq** [comment] 2021-07-09 15:28
@oowekyala You are right. Sorry for inconvenience. Somehow I've typed a wrong version of pmd. Of course pmd-plugin 3.14 depends on pmd 6.29.0 (https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-pmd-plugin/3.14.0)

**Comment by oowekyala** [comment] 2021-07-09 15:55
thanks for clarifying!
