### ISSUE TITLE
[apex] Apex PMD does not recognize Apex keyword "as", reports Sev 1 issue due to code not compiling, but code does compile

### ISSUE THREAD

**Issue by danviizr** [pmd/pmd#4689] opened 2023-09-25 15:17 UTC
**Affects PMD Version:** 

7.0.0-rc3

**Description:**

A sev 1 issue appears in category "Scanner Internal", files-must-compile when the valid "as" keyword is used in Apex.

See [Enforce User Mode for Database Operations](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_enforce_usermode.htm) for examples of "as" keyword

**Exception Stacktrace:**

```
PMDException: Error while parsing /Users/myuser/projects/myproject/classes/MyApexClass.cls Caused by: net.sourceforge.pmd.lang.ast.ParseException: apex.jorje.services.exception.ParseException: Syntax(error = UnexpectedToken(loc = (53, 16, 402, 404), token = 'as'))
```

**Code Sample demonstrating the issue:**

```java
Account acc = new Account(Name='test');
insert as user acc;
```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

1.  Add an Apex method to a project that uses the "as" keyword
2. Run PMD scan on the project
3. Observe sev 2 PMD finding due to code not compiling
4. Deploy the project using `sf source push`
5. Observe the reported class compiles successfully

**Running PMD through:** *CLI*

**Comment by adangel** [comment] 2023-09-28 06:35
Thanks for reporting.

However, this is a Duplicate of #3973 .

**Closed by adangel** 2023-09-28 06:35 UTC
Labels: a:bug, was:duplicate
