### ISSUE TITLE
[apex] Apex ant target logs inscrutable INFO statement

### ISSUE THREAD

**Issue by MisterSquishy** [pmd/pmd#621] opened 2017-09-14 17:30 UTC
Please, prefix the report title with the language it applies to within brackets, such as *[java]* or *[apex]*. If not specific to a language, you can use *[core]*

**Rule Set:** ALL: apexunit, braces, complexity, performance, security, style

**Description:** running PMD on Apex code always outputs an annoying INFO string, which will confuse my dev team:

[pmd] Sep 14, 2017 1:28:10 PM apex.jorje.parser.impl.BaseApexLexer dedupe
[pmd] INFO: Deduped array ApexLexer.DFA23_transition. Found 7927114 shorts which is 15MB not including array overhead. Removed 7204963 shorts which is 13MB not counting array overhead. Took 10ms.
[pmd] EmptyTest.cls:10:   Deeply nested if..then statements are hard to read

**Code Sample demonstrating the issue:**

```
<pmd shortFilenames="true" failuresPropertyName="totalFailures">
                    <ruleset>rulesets/apex/apexunit.xml</ruleset>
                    <ruleset>rulesets/apex/braces.xml</ruleset>
                    <ruleset>rulesets/apex/complexity.xml</ruleset>
                    <ruleset>rulesets/apex/performance.xml</ruleset>
                    <ruleset>rulesets/apex/security.xml</ruleset>
                    <ruleset>rulesets/apex/style.xml</ruleset>
                    <formatter type="text" toConsole="true">
                        <param name="linkPrefix" value="http://pmd.sourceforge.net/xref/"/>
                    </formatter>
                    <fileset dir="${basedir}/delta/classes/"/>
                </pmd>
```

**Running PMD through:** *[Ant]*

**Comment by jsotuyod** [comment] 2017-09-14 17:47
@MisterSquishy thanks for the report. This seems to be a duplicate of #500. A fix for it is already on master thanks to #503. It will be released on PMD 6.0.0

In the meantime, the workaround is: to create / edit the file `JRE_DIRECTORY/lib/logging.properties` and add the following line to the end, to disable the log output:

    BaseApexLexer.level = OFF

**Closed by jsotuyod** 2017-09-14 17:47 UTC
