### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to exclude rules [GuardLogStatement]; perhaps the rule name is mispelled?

### ISSUE THREAD

**Issue by miPlodder** [pmd/pmd#1859] opened 2019-06-08 08:34 UTC
**Affects PMD Version:** 

**Rule:**

logging-java.xml > GuardLogStatementJavaUtil

**Description:**

java.lang.IllegalArgumentException: Unable to exclude rules [GuardLogStatement]; perhaps the rule name is mispelled?

**Code Sample demonstrating the issue:**

[Code](https://github.com/apache/fineract-cn-mobile/tree/development/config/quality)

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

Gradle 5.1.1 (Android Studio)

**Comment by miPlodder** [comment] 2019-06-08 08:46
I started to face this issue after migrating to Gradle 5.1.1

**Comment by adangel** [comment] 2019-06-10 08:39
Upgrading gradle probably upgraded PMD as well.
Gradle 5.1.1 uses [PMD 6.8.0](https://github.com/gradle/gradle/blob/v5.1.1/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java#L51) by default. You can configure this yourself by setting the ["toolVersion" property](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.PmdExtension.html#org.gradle.api.plugins.quality.PmdExtension:toolVersion).

Your ruleset looks like it is from PMD5 and you should consider upgrading it to a PMD 6 ruleset. This means, you'll need to look, which rules you want and reference them one by one from the new categories.

For the problem at hand, this is already solved, see: #1794 

So you should be able to get it working with the current ruleset, if you set `toolVersion` to at least 6.14.0 (not, at the moment, the latest PMD version is 6.15.0).

I'm closing this as a duplicate of #1794 .

**Closed by adangel** 2019-06-10 08:39 UTC
