### ISSUE TITLE
[java] RuleViolationFactory.addViolation() throw exception while parameter 'message' contain  special character

### ISSUE THREAD

**Issue by ief2009** [pmd/pmd#1699] opened 2019-02-26 02:48 UTC
**Affects PMD Version:** 6.12.0

**Rule:** 

**Description:** all message are formatted while call RuleViolationFactory.addViolation(), but sometimes there is no need even cause exception.

**Code Sample demonstrating the issue:**
```java
public void messageWithSingleBrace() {
    RuleViolationFactory factory = JavaRuleViolationFactory.INSTANCE;
    factory.addViolation(new RuleContext(), new DuplicateImportsRule(), null, "message with \"{\"", null);
}
```

this  throw exception below:
```java
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.text.MessageFormat.applyPattern(MessageFormat.java:508)
	at java.text.MessageFormat.<init>(MessageFormat.java:362)
	at java.text.MessageFormat.format(MessageFormat.java:840)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.cleanup(AbstractRuleViolationFactory.java:26)
	at net.sourceforge.pmd.lang.rule.AbstractRuleViolationFactory.addViolation(AbstractRuleViolationFactory.java:35)
    ......


```

**Comment by ief2009** [comment] 2019-02-26 02:57
can i just modify AbstractRuleViolationFactory.cleanup() as below?

```java
private String cleanup(String message, Object[] args) {
    
    if (args == null || args.length == 0) {
        return message;
    }
    
    if (message != null) {
        // Escape PMD specific variable message format, specifically the {
        // in the ${, so MessageFormat doesn't bitch.
        final String escapedMessage = StringUtils.replace(message, "${", "$'{'");
        return MessageFormat.format(escapedMessage, args != null ? args : NO_ARGS);
    } else {
        return message;
    }
}
```

**Comment by oowekyala** [comment] 2019-02-26 14:26
I mean you could just quote the `{`: 
```java
"message with \"'{'\""
```
This is how the MessageFormat API is intended to be used. I think skipping MessageFormat when there's no arguments could only introduce inconsistencies and unexpected behaviour w.r.t. quoting. Adding an argument to a message that previously had none would mean you have to quote everything back, and would change the output message because now, single quotes would be interpreted.

I don't think this is needed or reasonable to implement.

**Comment by adangel** [comment] 2019-03-02 13:59
@ief2009 Could you elaborate a bit more, why you think, the current behavior is a problem?

given the code

```java
factory.addViolation(new RuleContext(), new DuplicateImportsRule(), null, "message with \"{\"", null);
```

You would have a unit test for your rule and see this fails, you you would just fix your rule end escape the bracket:

```java
factory.addViolation(new RuleContext(), new DuplicateImportsRule(), null, "message with \"'{'\"", null);
```

This code looks to me artificial. Where exactly did you run into this issue?

**Comment by jsotuyod** [comment] 2019-04-01 17:49
Given the change was rejected, and the unit test added… should we close this? @oowekyala @adangel

**Closed** 2019-04-07 03:56 UTC
