### ISSUE TITLE
[Swift] Parsing errors encountered with emoji

### ISSUE THREAD

**Issue by ghost** [pmd/pmd#2698] opened 2020-08-05 15:51 UTC
**Affects PMD Version:** 
6.26.0
[CPD]

**Description:**

I am using cpd to run a folder contains swift files. Following is the command I run, and errors encountered.

**Exception Stacktrace:**

```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file ServerUserService.swift at line 80, column 16.  Encountered: token recognition error at: '👤'
	at net.sourceforge.pmd.cpd.AntlrTokenizer.tokenize(AntlrTokenizer.java:44)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:139)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:108)
	at net.sourceforge.pmd.cpd.CPD.add(CPD.java:70)
	at net.sourceforge.pmd.cpd.CPD.addDirectory(CPD.java:80)
	at net.sourceforge.pmd.cpd.CPD.addRecursively(CPD.java:65)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourcesFilesToCPD(CPDCommandLineInterface.java:134)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.addSourceFilesToCPD(CPDCommandLineInterface.java:114)
	at net.sourceforge.pmd.cpd.CPDCommandLineInterface.main(CPDCommandLineInterface.java:87)
	at net.sourceforge.pmd.cpd.CPD.main(CPD.java:179)
Caused by: LexerNoViableAltException('👤')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:312)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:233)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:117)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
	at net.sourceforge.pmd.lang.antlr.AntlrTokenManager.getNextTokenFromAnyChannel(AntlrTokenManager.java:47)
	at net.sourceforge.pmd.lang.antlr.AntlrTokenManager.getNextToken(AntlrTokenManager.java:40)
	at net.sourceforge.pmd.cpd.token.internal.BaseTokenFilter.getNextToken(BaseTokenFilter.java:45)
	at net.sourceforge.pmd.cpd.AntlrTokenizer.tokenize(AntlrTokenizer.java:39)
	... 10 more
2020-08-05 18:45:06.480 CPDSwift[33372:1842414] Error occured on Parsing CPD XML output file : The operation couldn’t be completed. (com.google.GDataXML error -1.)
Command PhaseScriptExecution failed with a nonzero exit code
```

**Code Sample demonstrating the issue:**

```swift
if let userToken = userToken {
     print("👤 | User > Token: \(userToken)")
}
```

**Comment by jrtibbetts** [comment] 2021-05-27 21:04
The exact same thing happens if you use an alternative String delimiter like '#', e.g.

```
        var baseCommand = #"curl "\#(url.absoluteURL)""#
```

This is perfectly valid Swift, and runs just fine in the app. I had to replace all of them with `"`s, and then escape the other existing `"`s, in order to get CPD to work.

**Comment by oowekyala** [comment] 2021-05-27 21:34
@jrtibbetts this is not the same bug. Yours should have been fixed with #2666. Does this happen on a pmd version more recent than 6.31.0?

**Comment by jrtibbetts** [comment] 2021-05-27 23:14
I literally installed PMD for the first time today, via HomeBrew on macOS. It looks like it's 6.34.0.

**Comment by jrtibbetts** [comment] 2021-05-28 14:57
Hold that thought--I just rechecked it, and it's 6.30.0 on the laptop that I encountered the problem on, but 6.34.0 from the one where I typed that comment. 6.30.0 is on a 2019 MacBook Pro running macOS Catalina (10.15.7). The newer one is on an M1 MBP running Big Sur.

**Comment by oowekyala** [comment] 2021-05-28 15:11
I think it's more likely that the `\#` is not recognized as an escape but I haven't gotten around to test it. Can you open a new bug report please?

**Comment by jsotuyod** [comment] 2024-04-03 03:12
None of the issues described in this discussion are reproducible under PMD 7.0.0

**Closed by jsotuyod** 2024-04-03 03:12 UTC
Labels: a:bug, in:grammar
