### ISSUE TITLE
[java] Parse error on annotation fields with generics

### ISSUE THREAD

**Issue by scais** [pmd/pmd#206] opened 2017-01-25 14:41 UTC
Hello guys,

   I found an issue when analyzing open-source project 'caffeine' (https://github.com/ben-manes/caffeine). Can you please take a look?

**PMD version:**
5.5.2

**Rule Set:**
java-basic

**Description:**
```
Error while processing file: caffeine\src\test\java\com\github\benmanes\caffeine\cache\testing\CacheSpec.java
net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "=" "= "" at line 360, column 56.
Was expecting:
    "(" ...

        at net.sourceforge.pmd.lang.java.ast.JavaParser.generateParseException(JavaParser.java:10875)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.jj_consume_token(JavaParser.java:10759)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationMethodDeclaration(JavaParser.java:6396)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationTypeMemberDeclaration(JavaParser.java:6318)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationTypeBody(JavaParser.java:6259)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationTypeDeclaration(JavaParser.java:6194)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:482)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:222)
        at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:56)
        at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:95)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:142)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:80)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:47)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:79)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Code Sample demonstrating the issue:**

```
public @interface CacheSpec {
  // FIXME: A hack to allow the NEGATIVE loader's return value to be retained on refresh
  static final ThreadLocal<Interner<Integer>> interner =
      ThreadLocal.withInitial(Interners::newStrongInterner);
}
```

**Running PMD through:** *[CLI]*
```
java -cp * net.sourceforge.pmd.PMD -d "...caffeine\caffeine\src\test\java\com\github\benmanes\caffeine\cache\testing" -f text -R java-basic -verbose
```

**Comment by scais** [comment] 2017-01-25 15:18
Update - the same issue is being triggered in 'spring-framework'

```
Error while processing file: spring-framework\spring-web\src\main\java\org\springframework\web\bind\annotation\CrossOrigin.java
net.sourceforge.pmd.lang.java.ast.ParseException: Encountered " "=" "= "" at line 55, column 34.
Was expecting:
    "(" ...

        at net.sourceforge.pmd.lang.java.ast.JavaParser.generateParseException(JavaParser.java:10875)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.jj_consume_token(JavaParser.java:10759)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationMethodDeclaration(JavaParser.java:6396)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationTypeMemberDeclaration(JavaParser.java:6318)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationTypeBody(JavaParser.java:6259)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.AnnotationTypeDeclaration(JavaParser.java:6194)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.TypeDeclaration(JavaParser.java:482)
        at net.sourceforge.pmd.lang.java.ast.JavaParser.CompilationUnit(JavaParser.java:222)
        at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:56)
        at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:95)
        at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:142)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:80)
        at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:47)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:79)
        at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

the analyzed code:

```
	/**
	 * @deprecated as of Spring 5.0, in favor of using {@link CorsConfiguration#applyPermitDefaultValues}
	 */
	@Deprecated
	String[] DEFAULT_ORIGINS = { "*" };
```

**Comment by jsotuyod** [comment] 2017-01-25 16:00
The issue is confirmed, occurs only within annotations. I'm looking into a fix for this.

**Comment by jsotuyod** [comment] 2017-01-25 16:14
Just submitted a PR to fix this issue. Thanks again!

**Comment by ben-manes** [comment] 2017-01-25 21:06
@scais fyi, if it helps with your analysis of open-source projects, Caffeine has a [ruleSet](https://github.com/ben-manes/caffeine/blob/master/config/pmd/rulesSets.xml) configuration. The `src/main` is analyzed on every CI build using `./gradlew pmdMain -Dpmd`.

**Comment by jsotuyod** [comment] 2017-01-25 21:42
@ben-manes that's interesting. I wonder why you didn't see this before yourselves... Maybe we are not giving it enough visibility in xml / html reports... 

Any feedback is welcomed to help us improve pmd!

**Comment by ben-manes** [comment] 2017-01-25 21:49
@jsotuyod Its because I don't run findbugs or pmd on test code. That wouldn't be a bad idea and I was perhaps lazy by thinking it wasn't worth the effort.

In this case, the annotation is used to define a spec for a TestNG data provider. That way the test cases can generate every permutation that passes the constraints. Since the cache has many configuration options, it brute forces very high coverage which is helpful given the problem complexity. But some hacks were needed, hence the `FIXME`, which is okay in test code.

**Closed** 2017-01-27 19:58 UTC
Labels: bug
