### ISSUE TITLE
[java][core] Fatal error upgrading from 6.25.0 to 6.26.0

### ISSUE THREAD

**Issue by jbennett2091** [pmd/pmd#2705] opened 2020-08-06 17:36 UTC
**Affects PMD Version:** 

6.26.0

**Description:**

We changed from pmd.version 6.25.0 to 6.26.0 (no other change) and build now fails at pmd:pmd with "A required class was mi
ssing while executing org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd: javax/jms/Message".   This occurs on a number of different modules in our project, although the missing class changes from module to module

**Exception Stacktrace:**

[ERROR] Failed to execute goa          l org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd (pmd) on project
momni-server: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plug          in:3.13.0:pmd failed: A required class was mi
ssing while executing org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd: javax/jms/Message
[ERR       OR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-pmd-plugin:3.13.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/U                 sers/jb14684/.m2/repository/org/apache/maven/plugins/maven-pmd-plugin/3.13.0/maven-pm
d-plugin-3.13.0.jar
[ERROR]             1;31murls[1] = file:/C:/Users/jb14684/.m2/repository/net/sourceforge/pmd/pmd-core/6.26.0/pmd-core-6.26.0.jar
m
[ERROR] urls                 [2] = file:/C:/Users/jb14684/.m2/repository/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.jar
[ERROR] urls[3]                  = file:/C:/Users/jb14684/.m2/repository/com/beust/jcommander/1.72/jcommander-1.72.jar
[31mERROR] urls[4] = file:/C:/Users/jb14684/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8.jar
[ERROR] urls[5] = file:/C:/Users/jb14                 684/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.
1.jar
[ERROR] urls[6] = file:/C:/Users/jb14                 684/.m2/repository/org/apache/commons/commons-text/1.6/commons-text-1.6.jar
[m
[ERROR          ] urls[7] = file:/C:/Users/jb14684/.m2/repository/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
[ERROR] urls[8] = file:/C:/Users/jb14684/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar
[ERROR] urls[9] = file:/C:/Users/jb14684/.                 m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-dom.jar

[ERROR] urls[10] = file:/C:/Users/jb14684/.m2/repository/net/sourceforge/pmd/pmd-java/6.26.0/pmd-java-6.2                 6.0.jar
[m
[ERROR] urls[11] = file:/C:/Users/jb14684/.m2/repository/net/sourceforge/pmd/pmd-javascript/6.26.0/pmd-javascript
-6.26.0.jar
[ERROR] urls[12] = file:/C:/Users/jb14684/.m2/repository/org/mozilla                 /rhino/1.7.7.2/rhino-1.7.7.2.jar
[ERROR] urls[13] = file:/C:/Users/jb14684/.m2/repository/net/sourceforge/pmd/pmd-jsp/6.26.0/pmd-jsp-6.26.0.jar

[ERROR]                 murls[14] = file:/C:/Users/jb14684/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bea
n-1.4.2.jar
[ERROR] urls[15] = file:/C:/Users/jb14684/.m2/repository/org/sonatype/sisu/sisu-                 guice/2.1.7/sisu-guice-2.1.7-noao
p.jar
[ERROR] urls[16] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/shared/maven-artifact-transfer/0.10.0/m
aven-artifact-transfer-0.10.0.jar
[     1mERROR] urls[17] = file:/C:/Users/jb14684/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[m
[ERROR] urls[18] = file:/C:/Users/jb14684/.m2/repository/org/codehaus/plexus/p                 lexus-interpolation/1.14/plexus-int
erpolation-1.14.jar
[ERROR] urls[19] = file:/C:/Users/jb14684/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec
-dispatcher-1.3.jar
[ERROR] urls[20] = file:/C:/Users/jb14684/.m                 2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.
jar
[ERROR] urls[21] = file:/C:/Users/jb14684/.m2/repository/org/codehaus/plexus/plexus-component-annota                 tions/1.7.1/p
lexus-component-annotations-1.7.1.jar
[ERROR] urls[22] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.
0.1/maven-common-artifact-filters-3.0.1.jar
[ERROR] urls[23] = file:/C:/Users/jb14684/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[m
[ERROR] urls[24] = file:/C:/Users/                 jb14684/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar

[ERROR] urls[25] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api
-1.7.jar
[ERROR] urls[26] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-loggi
ng-api-1.7.jar
[ERROR] urls[27] = file:/C:/Users/jb1468                 4/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.7/doxia-
decoration-model-1.7.jar
[ERROR] urls[28] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.7/d                 oxia-sit
e-renderer-1.7.jar
[ERROR] urls[29] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar

[ERROR] urls[30] = file:/C:/Users/jb14684/.m2/reposito                 ry/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
[ERROR] urls[31] = file:/C:/Users/jb14684/.m2/repository/xmlunit/xmlunit/1.5/xmlunit-1.5.jar
[ERROR] urls[32] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-sk                 in-model/1.7/doxia-skin-m
odel-1.7.jar
[ERROR] urls[33] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-modu
le-xhtml-1.7.jar
[ERROR] urls[34]                  = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module
-fml-1.7.jar
[ERROR] urls[35] = file:/C:/Users/jb14684/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n                 -1
.0-beta-7.jar
[ERROR] urls[36] = file:/C:/Users/jb14684/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[37] = file:/C:/Users/jb14684/.m2/repository/org/codehaus/plexus/plexus                 -velocity/1.1.7/plexus-velocit
y-1.1.7.jar
[ERROR] urls[38] = file:/C:/Users/jb14684/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
[ERROR] urls[39] = file:/C                 :/Users/jb14684/.m2/repository/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.
0.jar
[ERROR] urls[40] = file:/C:/Users/jb14684/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanut
ils-1.7.0.jar
[ERROR] urls[41] = file:/C:/Users/jb14684/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1
.8.jar
[ERROR] urls[42] = file:/C:/Users/jb14684/.m2/repository/commons-chain/commons-chain/1.1/commons-chain-1                 .1.jar

[ERROR] urls[43] = file:/C:/Users/jb14684/.m2/repository/commons-validator/commons-validator/1.3.1/commons-valida
tor-1.3.1.jar
[ERROR] urls[44] = file:/C:/Users/jb14684/.m2/repository/dom4j/dom4j/1.1/dom4j-1.1.jar                  [m
[ERROR] urls[45] = file:/C:/Users/jb14684/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[46] = file:/C:/Users/jb14684/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar
[ERROR] urls[47] = file:/C:/Users/jb14684/.m2/repository/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.ja
r
[ERROR] urls[48] = file:/C:/Users/jb14684/.m2/repository/antlr/antlr/2.7.2/antlr-2.7.2.jar
[ERROR          ] urls[49] = file:/C:/Users/jb14684/.m2/repository/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.
8.jar
[ERROR] urls[50] = file:/C:/Users/jb14684/.m2/repository/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.
jar
[ERROR] urls[51] = file:/C:/Users/jb14684/.m2/repository/commons-collections/commons-collections/3.2.1/commons-co
llections-3.2.1.jar
[ERROR] urls[52] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/repor                 ting/maven-reporting-api/3.0/maven
-reporting-api-3.0.jar
[ERROR] urls[53] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/3.0.0/ma
ven-reporting-impl-3.0.0.jar
[       ERROR] urls[54] = file:/C:/Users/jb14684/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-s
hared-utils-3.2.0.jar
[ERROR] urls[55] = file:/C:/Users/jb14684/.m2/repository/org/codehaus/plexus/plexus-resourc                 es/1.0.1/plexus-resour
ces-1.0.1.jar
[ERROR] urls[56] = file:/C:/Users/jb14684/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0
.24.jar
[ERROR] urls[57                 ] = file:/C:/Users/jb14684/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.
5.3.jar
[ERROR] urls[58] = file:/C:/Users/jb14684/.m2/repository/org/apache/httpcomponents                 /httpcore/4.4.6/httpcore-4.4.6.
jar
[ERROR] urls[59] = file:/C:/Users/jb14684/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.
jar
[ERROR] urls[60]                  = file:/C:/Users/jb14684/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  fro                 m realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : javax.jms.Message
[ERROR] -> [Help 1]

```
# Copy-paste the stack trace here
```

   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:169)
       mat org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions (MojoExecutor.java:355)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:200)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycl       e.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java
:190)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java
:186)
    at     java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecuto       r$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: javax/jms/Message
    at java.lang.Class.getDeclaredMethods0 (Native Method)
    at java.lang.Class.privateGetDeclaredMethods (Class.java:2701)
    at java.lang.Class.privateGetPubl       icMethods (Class.java:2902)
    at java.lang.Class.getMethods (Class.java:1615)
    at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init> (ImportWrapper.java:44)
    at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init> (ImportWrapper.java:33)
    at net.sourceforge.pmd.lang.java.rule.bestpractices.Unuse       dImportsRule.visit (UnusedImportsRule.java:131)
    at net.sourceforge.pmd.lang.java.ast.ASTImportDeclaration.jjtAccept (ASTImportDeclaration.java:143)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:219)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (Ab           stractJavaRule.java:391)
    at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit (UnusedImportsRule.java:57)
    at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept (ASTCompilationUnit.java:44)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visitAll (AbstractJavaRule.java:162)
    at net.sourceforge.pm       d.lang.java.rule.AbstractJavaRule.apply (AbstractJavaRule.java:156)
    at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply (AbstractDelegateRule.java:336)
    at net.sourceforge.pmd.RuleSet.apply (RuleSet.java:575)
    at net.sourceforge.pmd.RuleSets.apply (RuleSets.java:148)
    at net.sourceforge.pmd.Sour       ceCodeProcessor.processSource (SourceCodeProcessor.java:194)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache (SourceCodeProcessor.java:107)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode (SourceCodeProcessor.java:89)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode (SourceCodeProcessor.java:51)
    at        net.sourceforge.pmd.processor.PmdRunnable.call (PmdRunnable.java:78)
    at net.sourceforge.pmd.processor.PmdRunnable.call (PmdRunnable.java:24)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.           java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javax.jms.Message
      1mat java.net.URLClassLoader.findClass (URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:418)
    at net.sourceforge.pmd.util.ClasspathClassLoader.loadClass (ClasspathClassLoader.java:123)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:351)
    at java.lang.Class.getDeclaredMethods0 (Na           tive Method)
    at java.lang.Class.privateGetDeclaredMethods (Class.java:2701)
    at java.lang.Class.privateGetPublicMethods (Class.java:2902)
    at java.lang.Class.getMethods (Class.java:1615)
    at net.sourceforge.pmd.lang.java.ast.internal.ImportWrapper.<init> (ImportWrapper.java:44)
    at net.sourceforge.pmd.lang.java.ast.internal.Impor       tWrapper.<init> (ImportWrapper.java:33)
    at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit (UnusedImportsRule.java:131)
    at net.sourceforge.pmd.lang.java.ast.ASTImportDeclaration.jjtAccept (ASTImportDeclaration.java:143)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:219)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.visit (AbstractJavaRule.java:391)
    at net.sourceforge.pmd.lang.java.rule.bestpractices.UnusedImportsRule.visit (UnusedImportsRule.java:57)
    at net.sourceforge.pmd.lang.java.ast.ASTCompilationUnit.jjtAccept (ASTCompilationUnit.java:44)
    at net.sourceforge.pmd.lang.       java.rule.AbstractJavaRule.visitAll (AbstractJavaRule.java:162)
    at net.sourceforge.pmd.lang.java.rule.AbstractJavaRule.apply (AbstractJavaRule.java:156)
    at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply (AbstractDelegateRule.java:336)
    at net.sourceforge.pmd.RuleSet.apply (RuleSet.java:575)
    at net.sourceforge.pmd.RuleSets.a       pply (RuleSets.java:148)
    at net.sourceforge.pmd.SourceCodeProcessor.processSource (SourceCodeProcessor.java:194)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCodeWithoutCache (SourceCodeProcessor.java:107)
    at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode (SourceCodeProcessor.java:89)
    at net.sourceforge.pmd.SourceC       odeProcessor.processSourceCode (SourceCodeProcessor.java:51)
    at net.sourceforge.pmd.processor.PmdRunnable.call (PmdRunnable.java:78)
    at net.sourceforge.pmd.processor.PmdRunnable.call (PmdRunnable.java:24)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call (        [1mExecutors.java:511)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java       .lang.Thread.run (Thread.java:748)

**Code Sample demonstrating the issue:**

```

Sorry, not provided.

```

**Steps to reproduce:**

Please provide detailed steps for how we can reproduce the bug.

mvn clean verify
- maven 3.6.3
- java AdoptOpenJDK (hotspot) 1.8.0_262
- maven-pmd-plugin: 3.13.0

Manifests on both Windows (10) and Linux (ubuntu) 
Manifests on both 1.8.0_262 (adpt) and 11.0.8 (adpt)

**Running PMD through:** *[CLI | Ant | Maven | Gradle | Designer | Other]*

                                <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-pmd-plugin</artifactId>
                                        <version>${pmd.plugin.version}</version>
                                        <dependencies>
                                                <dependency>
                                                        <groupId>net.sourceforge.pmd</groupId>
                                                        <artifactId>pmd-core</artifactId>
                                                        <version>${pmd.version}</version>
                                                </dependency>
                                                <dependency>
                                                        <groupId>net.sourceforge.pmd</groupId>
                                                        <artifactId>pmd-java</artifactId>
                                                        <version>${pmd.version}</version>
                                                </dependency>
                                                <dependency>
                                                        <groupId>net.sourceforge.pmd</groupId>
                                                        <artifactId>pmd-javascript</artifactId>
                                                        <version>${pmd.version}</version>
                                                </dependency>
                                                <dependency>
                                                        <groupId>net.sourceforge.pmd</groupId>
                                                        <artifactId>pmd-jsp</artifactId>
                                                        <version>${pmd.version}</version>
                                                </dependency>
                                        </dependencies>
                                        <executions>
                                                <execution>
                                                        <id>check</id>
                                                        <phase>verify</phase>
                                                        <goals>
                                                                <goal>check</goal>
                                                        </goals>
                                                </execution>
                                        </executions>
                                        <configuration>
                                                <rulesets>
                                                        <ruleset>${pmd.ruleset}</ruleset>
                                                </rulesets>
                                                <aggregate>false</aggregate>
                                                <excludeRoots>target</excludeRoots>
                                                <failurePriority>4</failurePriority>
                                                <maxAllowedViolations>0</maxAllowedViolations>
                                                <failOnViolation>true</failOnViolation>
                                                <printFailingErrors>true</printFailingErrors>
                                                <verbose>false</verbose>
                                                <includeTests>true</includeTests>
                                                <analysisCache>true</analysisCache>
                                                <analysisCacheLocation>${user.home}/pmd-cache/${project.artifactId}</analysisCacheLocation>
                                        </configuration>
                                </plugin>

**Comment by adangel** [comment] 2020-08-10 18:07
Thanks for reporting. This is a duplicate of #2663 .

**Closed by adangel** 2020-08-10 18:07 UTC
Labels: a:bug, was:duplicate
